## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
  - os: linux
  - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'Pkg.clone("https://github.com/samridler/ArchGDAL.jl.git"); Pkg.build("ArchGDAL")'
  - julia --color=yes -e 'Pkg.add("WebSockets"); Pkg.pin("WebSockets", v"0.4.0")'
  - julia --color=yes -e 'Pkg.clone(pwd()); Pkg.build("JEMSS"); Pkg.test("JEMSS"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("JEMSS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("JEMSS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
